// src/components/vod/TimestampText.svelte
<script lang="ts">
	let { offsetSeconds }: { offsetSeconds: number } = $props();

	function formatTimestamp(offsetSeconds: number): string {
		const hours = Math.floor(offsetSeconds / 3600);
		const minutes = Math.floor((offsetSeconds % 3600) / 60);
		const seconds = Math.floor(offsetSeconds % 60);
		
		if (hours > 0) {
			return `${hours}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
		}
		return `${minutes}:${seconds.toString().padStart(2, '0')}`;
	}
</script>

<span class="font-mono text-sm">
	{formatTimestamp(offsetSeconds)}
</span>

// src/components/react/vod/TimestampText.tsx
import React from 'react';

interface TimestampTextProps {
  offsetSeconds: number;
}

const TimestampText: React.FC<TimestampTextProps> = ({ offsetSeconds }) => {
  const formatTimestamp = (seconds: number): string => {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const remainingSeconds = seconds % 60;
    
    if (hours > 0) {
      return `${hours}:${minutes.toString().padStart(2, '0')}:${remainingSeconds.toString().padStart(2, '0')}`;
    }
    return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
  };

  return (
    <span className="font-mono text-sm">
      {formatTimestamp(offsetSeconds)}
    </span>
  );
};

export default TimestampText;
